# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e48b9ce264d51269f5692564054f434476cee91c38559e795bb710c48f339fa0cc9659c98b53ab694361fbe07cdab5dd8973045fdb422231fad410193b56273d

test:
  secret_key_base: b9cb4e2e14e6617665ffbe00255a669c8d11ae522b06b2680d5be8d1725ee1cc1f550c78969de750e3d1322cb9bfdbc46a58e84030716fdce2f24b6d90f51b53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
